services:
  db:
    image: mongo:latest
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - './db/data/db-files:/data/db'
      - './db/init/:/docker-entrypoint-initdb.d/'
    ports:
      - 27017:27017
    networks:
      - backend

  svc-auth:
    build: ./auth
    env_file:
      - .env
    networks:
      - backend
    ports:
      - ${SVC_AUTH_PORT}:${SVC_AUTH_PORT}

  svc-users:
    build: ./users
    env_file:
      - .env
    networks:
      - backend
    ports:
      - ${SVC_USERS_PORT}:${SVC_USERS_PORT}

  gateway:
    build: ./gateway
    env_file:
      - .env
    networks:
      - backend
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}

networks:
  backend:
    driver: bridge
